# Generated by Django 4.2.27 on 2026-02-11 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('PENDING', '검토대기'), ('REVIEWING', '재무조정중'), ('FINALIZED', '최종확정')], default='DRAFT', max_length=20)),
                ('last_year_amount', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('org_type', models.CharField(default='dept', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('REQUESTOR', '작성자'), ('REVIEWER', '검토자'), ('ADMIN', '관리자/재무팀')], default='REQUESTOR', max_length=20)),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_mgmt.organization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BudgetTransfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField()),
                ('reason', models.TextField()),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='budget_evidence/%Y/%m/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('from_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_out', to='budget_mgmt.budgetentry')),
                ('to_entry', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers_in', to='budget_mgmt.budgetentry')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('level', models.IntegerField()),
                ('subject_type', models.CharField(choices=[('income', '수입'), ('expense', '지출')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='budget_mgmt.budgetsubject')),
            ],
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_mgmt.organization'),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='budget_mgmt.budgetsubject'),
        ),
        migrations.CreateModel(
            name='BudgetDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.BigIntegerField()),
                ('qty', models.FloatField()),
                ('freq', models.IntegerField(default=1)),
                ('unit', models.CharField(max_length=20)),
                ('sub_label', models.CharField(blank=True, max_length=20, null=True)),
                ('source', models.CharField(max_length=50)),
                ('is_rate', models.BooleanField(default=False)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='budget_mgmt.budgetentry')),
            ],
        ),
        migrations.CreateModel(
            name='ApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(max_length=20, null=True)),
                ('to_status', models.CharField(max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='budget_mgmt.budgetentry')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='budgetentry',
            unique_together={('subject', 'organization', 'year')},
        ),
    ]
