# Generated by Django 4.2.27 on 2026-02-11 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='budget_mgmt.organization'),
        ),
    ]
