# Generated by Django 4.2.27 on 2026-02-11 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0002_budgetdetail_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubject',
            name='erpnext_account',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='erpnext_cost_center',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
