# Generated by Django 4.2.27 on 2026-02-11 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_mgmt', '0003_budgetsubject_erpnext_account_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='budget_category',
            field=models.CharField(choices=[('ORIGINAL', '???'), ('SUPPLEMENTAL', '??'), ('CARRYOVER', '??')], default='ORIGINAL', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='carryover_type',
            field=models.CharField(choices=[('NONE', '-'), ('SPECIFIC', '??'), ('ACCIDENT', '??'), ('CONTINUING', '??')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='supplemental_round',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_transfers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='reject_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgettransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', '??'), ('APPROVED', '??'), ('REJECTED', '??')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='SpendingLimitRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_unit_price', models.BigIntegerField()),
                ('unit', models.CharField(max_length=20)),
                ('enforcement', models.CharField(choices=[('WARN', '??'), ('BLOCK', '??')], default='WARN', max_length=10)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='limit_rules', to='budget_mgmt.budgetsubject')),
            ],
        ),
        migrations.CreateModel(
            name='BudgetExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateField()),
                ('amount', models.BigIntegerField()),
                ('description', models.CharField(max_length=255)),
                ('document_no', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='budget_mgmt.budgetentry')),
            ],
        ),
    ]
