# Generated by Django 4.2.27 on 2026-02-11 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0004_budgetentry_budget_category_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='budgetentry',
            unique_together={('subject', 'organization', 'year', 'supplemental_round')},
        ),
        migrations.CreateModel(
            name='BudgetVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('round', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('DRAFT', '작성중'), ('PENDING', '심의중'), ('CONFIRMED', '확정')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('year', 'round')},
            },
        ),
    ]
