# Generated by Django 4.2.27 on 2026-02-11 14:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0005_alter_budgetentry_unique_together_budgetversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntrustedProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('PLANNED', '계획'), ('ACTIVE', '진행'), ('CLOSED', '종료')], default='PLANNED', max_length=20)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entrusted_projects', to='budget_mgmt.organization')),
            ],
            options={
                'unique_together': {('organization', 'year', 'code')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='budgetentry',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='entrusted_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='budget_mgmt.entrustedproject'),
        ),
        migrations.AlterUniqueTogether(
            name='budgetentry',
            unique_together={('subject', 'organization', 'entrusted_project', 'year', 'supplemental_round')},
        ),
    ]
