# Generated by Django 4.2.27 on 2026-02-11 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0007_budgetdetail_evidence_fields'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetentry',
            options={'verbose_name': 'Budget Entry', 'verbose_name_plural': 'Budget Entries'},
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='budget_category',
            field=models.CharField(choices=[('ORIGINAL', 'Original'), ('SUPPLEMENTAL', 'Supplemental'), ('CARRYOVER', 'Carryover')], default='ORIGINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='carryover_type',
            field=models.CharField(choices=[('NONE', 'None'), ('SPECIFIC', 'Specific'), ('ACCIDENT', 'Accident'), ('CONTINUING', 'Continuing')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('REVIEWING', 'Reviewing'), ('FINALIZED', 'Finalized')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetsubject',
            name='subject_type',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=10),
        ),
        migrations.AlterField(
            model_name='budgettransfer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrustedproject',
            name='status',
            field=models.CharField(choices=[('PLANNED', 'Planned'), ('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='PLANNED', max_length=20),
        ),
        migrations.AlterField(
            model_name='spendinglimitrule',
            name='enforcement',
            field=models.CharField(choices=[('WARN', 'Warning'), ('BLOCK', 'Block')], default='WARN', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTOR', 'Requestor'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin')], default='REQUESTOR', max_length=20),
        ),
    ]
