# Generated by Django 4.2.27 on 2026-02-11 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0008_alter_budgetentry_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
