# Generated by Django 4.2.27 on 2026-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0009_budgetdetail_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetdetail',
            name='sort_order',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
