# Generated by Django 4.2.27 on 2026-02-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0010_alter_budgetdetail_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='currency_unit',
            field=models.CharField(default='원', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetdetail',
            name='freq_unit',
            field=models.CharField(default='회', max_length=20),
        ),
    ]
