# Generated by Django 4.2.27 on 2026-02-11 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0011_budgetdetail_currency_unit_budgetdetail_freq_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='budget_mgmt.organization'),
        ),
    ]
