# Generated by Django 4.2.27 on 2026-02-12 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0013_alter_budgetdetail_sort_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CLOSED', 'Closed')], default='DRAFT', max_length=20),
        ),
    ]
