# Generated by Django 4.2.27 on 2026-02-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0014_alter_budgetversion_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetversion',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='guidelines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
