# Generated by Django 4.2.27 on 2026-02-19 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0015_budgetversion_end_date_budgetversion_guidelines_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='entrustedproject',
            name='source_project',
            field=models.ForeignKey(blank=True, help_text='이전 연도 사업 등 예산 구성을 차용할 원본 사업', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_projects', to='budget_mgmt.entrustedproject', verbose_name='차용 원본 사업'),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='budget_category',
            field=models.CharField(choices=[('ORIGINAL', '본예산'), ('SUPPLEMENTAL', '추경'), ('CARRYOVER', '이월')], default='ORIGINAL', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='carryover_type',
            field=models.CharField(choices=[('NONE', '없음'), ('SPECIFIC', '명시이월'), ('ACCIDENT', '사고이월'), ('CONTINUING', '계속비이월')], default='NONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='status',
            field=models.CharField(choices=[('DRAFT', '작성중'), ('PENDING', '상신됨'), ('REVIEWING', '검토중'), ('FINALIZED', '확정됨')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='budgetversion',
            name='status',
            field=models.CharField(choices=[('DRAFT', '준비중'), ('PENDING', '접수중'), ('CONFIRMED', '확정됨'), ('CLOSED', '마감됨')], default='DRAFT', max_length=20),
        ),
        migrations.AlterField(
            model_name='entrustedproject',
            name='status',
            field=models.CharField(choices=[('PLANNED', '계획됨'), ('ACTIVE', '활성'), ('CLOSED', '종료')], default='PLANNED', max_length=20),
        ),
    ]
