# Generated by Django 4.2.27 on 2026-02-19 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0016_entrustedproject_source_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='budgetsubject',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'ordering': ['sort_order', 'id']},
        ),
        migrations.AddField(
            model_name='budgetsubject',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='organization',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
