# Generated by Django 4.2.27 on 2026-02-19 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0017_add_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='before_snapshot',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='budgetdetail',
            name='transfer_source_detail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transferred_details', to='budget_mgmt.budgetdetail'),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='creation_mode',
            field=models.CharField(choices=[('NEW', '신규작성'), ('TRANSFER', '이관작성')], default='NEW', max_length=20),
        ),
        migrations.AddField(
            model_name='budgetversion',
            name='source_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_versions', to='budget_mgmt.budgetversion'),
        ),
    ]
