# Generated by Django 4.2.27 on 2026-02-19 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0018_budgetdetail_before_snapshot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='executed_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='remaining_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='budgetentry',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('REQUESTOR', 'Requestor'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin'), ('ORG_VIEWER', 'Org Viewer')], default='REQUESTOR', max_length=20),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['year', 'organization'], name='budget_mgmt_year_2a1d43_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['status'], name='budget_mgmt_status_ba6228_idx'),
        ),
    ]
