# Generated by Django 4.2.27 on 2026-02-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0019_budgetentry_executed_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('REVIEWER', 'Reviewer'), ('ADMIN', 'Admin'), ('ORG_VIEWER', 'Org Viewer'), ('REQUESTOR', 'Requestor')], default='STAFF', max_length=20),
        ),
    ]
