# Generated by Django 4.2.27 on 2026-02-24 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0021_add_submission_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='budget_mgmt.budgetsubject'),
        ),
        migrations.AlterField(
            model_name='submissioncomment',
            name='comment_type',
            field=models.CharField(choices=[('DONE', '작성완료'), ('REQUEST', '수정요청'), ('QUESTION', '질문'), ('ANSWER', '답변')], default='DONE', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('STAFF', 'Staff'), ('MANAGER', 'Manager'), ('ADMIN', 'Admin'), ('ORG_VIEWER', 'Org Viewer'), ('REQUESTOR', 'Requestor'), ('REVIEWER', 'Reviewer')], default='STAFF', max_length=20),
        ),
    ]
