# Generated by Django 4.2.27 on 2026-02-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0022_update_submission_comment_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='submissioncomment',
            name='entrusted_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to='budget_mgmt.entrustedproject'),
        ),
    ]
