# Generated by Django 4.2.27 on 2026-02-24 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_mgmt', '0023_submissioncomment_entrusted_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportingDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='supporting_docs/%Y/%m/')),
                ('filename', models.CharField(max_length=255)),
                ('file_size', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='supporting_documents', to=settings.AUTH_USER_MODEL)),
                ('entrusted_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budget_mgmt.entrustedproject')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budget_mgmt.organization')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budget_mgmt.budgetsubject')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_documents', to='budget_mgmt.budgetversion')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
