# Generated by Django 4.2.27 on 2026-02-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0024_supportingdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetsubject',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
