# Generated by Django 4.2.27 on 2026-02-25 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0025_budgetsubject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetversion',
            name='guidelines_file',
            field=models.FileField(blank=True, null=True, upload_to='version_guidelines/'),
        ),
    ]

