# Generated by Django 4.2.27 on 2026-02-25 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0027_budgetdetail_author_budgetdetail_updated_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_users', to='budget_mgmt.organization', verbose_name='소속 팀'),
        ),
    ]
