# Generated by Django 4.2.27 on 2026-02-25 06:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budget_mgmt', '0028_userprofile_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='approvallog',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AddField(
            model_name='approvallog',
            name='action',
            field=models.CharField(db_index=True, default='STATUS_CHANGE', max_length=50),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='log_type',
            field=models.CharField(choices=[('WORKFLOW', 'Workflow'), ('AUTH', 'Auth'), ('CRUD', 'CRUD'), ('SYSTEM', 'System')], db_index=True, default='WORKFLOW', max_length=20),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='method',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='resource_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='resource_type',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='status_code',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='approvallog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_logs', to='budget_mgmt.budgetentry'),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='from_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='approvallog',
            name='to_status',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
