# Generated by Django 4.2.27 on 2026-02-25 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0029_alter_approvallog_options_approvallog_action_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['year', 'supplemental_round'], name='budget_mgmt_year_57ad2a_idx'),
        ),
        migrations.AddIndex(
            model_name='budgetentry',
            index=models.Index(fields=['organization', 'year', 'supplemental_round'], name='budget_mgmt_organiz_fb0d49_idx'),
        ),
    ]
