# Generated by Django 4.2.27 on 2026-02-25 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_mgmt', '0030_budgetentry_budget_mgmt_year_57ad2a_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetdetail',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
