export const VERSION_INTAKE_STRINGS = {
    // Labels & Titles
    pageTitle: '접수 관리',
    listTitle: '접수 목록',
    detailTitle: '접수 상세',
    masterTitle: '예산서 마스터',
    roundDetail: '회차 상세',
    round: '회차',
    inputPeriod: '입력 기간',
    newRoundBtn: '신규 예산서 접수',
    editRoundBtn: '회차 정보 수정',
    refreshStatus: '현황 새로고침',
    goToList: '목록으로',
    progressByDept: '부서별 진행 현황',
    bulkUploadTitle: '예산 항목 일괄 등록',
    exportOfficialBook: '공식 예산서 출력',

    // Table Headers
    no: '번호',
    year: '연도',
    name: '예산명',
    period: '기간',
    startDate: '시작일',
    endDate: '종료일',
    createdAt: '생성일',
    defaultSort: '기본(활성/연도)',
    dday: 'D-day',
    status: '상태',
    currentStatus: '현재 상태',
    statusControl: '상태 제어',
    management: '관리',
    dept: '부서',
    entryCount: '항목 수',
    totalAmount: '예산 합계',
    sourceRound: '기초데이터 원본',

    // Status Labels
    draft: '준비중',
    pending: '제출대기',
    confirmed: '확정',
    closed: '마감',
    active: '진행',

    // Form Labels
    applyYear: '적용 연도',
    roundName: '예산명칭',
    createMode: '기초데이터 설정',
    newCreate: '빈 상태로 시작',
    copyRound: '기존 회차 불러오기',
    originalRound: '불러올 회차',
    selectOriginal: '원본 회차 선택',
    copyNotice: '불러온 데이터는 당초 예산액 기준으로 저장되며, 증감액은 현예산액과 기존 예산액의 차이로 표시됩니다.',
    periodSetting: '입력 접수 기간 설정',
    guidelinesLabel: '부서별 작성 지침(공통)',
    guidelinesPlaceholder: '예산 작성 시 부서에서 참고할 지침을 입력하세요.',
    fileUploadLabel: '첨부 파일 등록',
    currentFile: '현재 파일: ',
    uploadPlaceholder: '파일을 드래그하거나 클릭하여 업로드하세요.',
    removeFile: '파일 제거',

    // Placeholders & Helpers
    searchPlaceholder: '사업명 검색..',
    namePlaceholder: '예: 2027년 본예산',
    bulkFormat: '형식: `subject_code, org_code, name, price, qty` (콤마 구분, 줄 단위)',
    bulkExample: '예: 1101, D001, 사무용품, 50000, 2',
    noData: '표시할 데이터가 없습니다.',
    noProgressData: '표시할 진행 현황 데이터가 없습니다.',
    loadingProgress: '진행 현황을 불러오는 중...',
    periodUndefined: '기간 미정',

    // Buttons
    save: '저장',
    cancel: '취소',
    delete: '삭제',
    deactivate: '비활성화',
    edit: '수정',
    view: '보기',
    upload: '업로드 실행',

    // Messages & Alerts
    confirmDelete: (name) => `"${name}" 버전을 삭제하시겠습니까? 관련 데이터도 모두 삭제됩니다.`,
    deleteSuccess: '삭제했습니다.',
    deleteFail: '삭제 실패',
    alreadyClosed: '이미 마감된 버전입니다.',
    confirmDeactivate: (name) => `"${name}" 버전을 비활성화(마감)하시겠습니까?`,
    deactivateSuccess: '비활성화했습니다.',
    changeFail: '변경 실패',
    transferRequired: '기초데이터 불러오기를 선택한 경우 원본 회차를 선택해야 합니다.',
    newRoundName: (year) => `${year}년 신규 회차`,
    createSuccess: (clonedCount) => {
        const extra = clonedCount > 0 ? `\n불러온 항목: ${clonedCount.toLocaleString()}건` : '';
        return `신규 예산서가 접수되었습니다.${extra}`;
    },
    createFail: '생성 실패',
    updateSuccess: '버전 정보가 업데이트되었습니다.',
    updateFail: '상태 변경 실패',
    saveSuccess: '버전 정보가 저장되었습니다.',
    saveFail: '저장 실패',
    inputRequired: '항목을 입력해 주세요.',
    uploadSuccess: (created, updated) => `업로드 완료: ${created} 생성, ${updated} 업데이트`,
    uploadFail: '업로드 실패',
    exportOfficialBookDone: '공식 예산서 파일을 다운로드했습니다.',
    exportOfficialBookFail: '공식 예산서 출력 중 오류가 발생했습니다.',
    sourceVersionEmpty: '선택한 원본 회차에 예산 항목이 없습니다. 다른 회차를 선택하거나 빈 상태로 시작하세요.',
    closeSuccess: '회차를 마감했습니다.',
    closeFail: '마감 처리 중 오류가 발생했습니다.',
    reopenSuccess: '마감을 해제했습니다.',
    reopenFail: '마감 해제 중 오류가 발생했습니다.',
    confirmClose: (name) => `"${name}" 회차를 마감합니까?\n마감 후에는 모든 편집이 잠깁니다.`,
    confirmReopen: (name) => `"${name}" 회차의 마감을 해제합니까?`,

    // Summary card labels
    summaryTotalRounds: '전체 예산서',
    summaryActiveRound: '진행 중 회차',
    summaryDeptStatus: '부서 현황',
    summaryCompleted: '완료',
    summaryInProgress: '진행중',
    summaryNotStarted: '미시작',
    summaryTotalEntries: '전체 항목',
    summaryTotalAmount: '합계 금액',
    summaryDeadline: '마감 기한',
    summaryNoPending: '진행 중인 회차 없음',

    // New strings for VersionList
    listMainTitle: '예산서 목록',
    layoutCard: '카드',
    layoutList: '목록',
    layoutCardTitle: '카드 보기',
    layoutListTitle: '목록 보기',
    sortTitle: '정렬 항목',
    sortDirTitle: '정렬 방향 전환',
    sortDirAsc: '오름차순',
    sortDirDesc: '내림차순',
    batchSelected: (count) => `${count}개 선택됨`,
    batchStart: '접수 개시',
    batchClose: '일괄 마감',
    batchDelete: '일괄 삭제',
    yearUnit: '년도',
    rankUnit: '번째 예산',
    periodNotSet: '기간 미설정',
    guidelinesExist: '있음',
    guidelinesNone: '없음',
    guidelineBadge: '작성 지침 있음',
    deptProgress: '부서 편성 현황',
    statsCompletedIcon: '✅ 완료',
    statsInProgressIcon: '⏳ 진행',
    statsNotStartedIcon: '⚪ 미시작',
    selectAll: '전체 선택',
    unselectAll: '선택 해제',
    batchSelectTitle: '일괄 작업용 선택',
    idLabel: 'ID',
    reopen: '재개',
    close: '마감',

    // Stats
    totalEntries: '전체 항목 수',
    totalSum: '전체 예산 합계',
};
